/*
 * generated by Xtext 2.14.0
 */
package org.xtext.grammarxml


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class GrammarXMLStandaloneSetup extends GrammarXMLStandaloneSetupGenerated {

	def static void doSetup() {
		new GrammarXMLStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
